# Generated by Django 6.0.3 on 2026-05-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_convenio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convenio',
        ),
        migrations.RemoveField(
            model_name='calculohistorico',
            name='convenio',
        ),
        migrations.AddField(
            model_name='calculohistorico',
            name='convenio_nome',
            field=models.CharField(default='Antigo', max_length=100),
            preserve_default=False,
        ),
    ]
